### ISSUE TITLE
RF data files and functions missing

### ISSUE THREAD

**Issue by ttriche** [BernsteinLab/aml2019#2]
```
tim@tim-ThinkPad-T470:~/Dropbox/TricheLab/TARGET_AML/Bernstein_scAML/aml2019/04 Random forest classifier$ Rscript 1_RFtrain.R
randomForest 4.6-14
Type rfNews() to see new features/changes/bug fixes.
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/home/tim/DropboxPartners/Single-cell AML/Analysis/AnalysisVolker/functions_general.vh20180105.R': No such file or directory
Execution halted
```

The other script in the directory also fails due to the .Rdata files not being available. 

The paper is great, but the code is far from complete. Shame on the reviewers for not running any of it.

**Comment by kyriakopou** [comment]
I think nobody ever tried to run this code. Completely agree with the above comment.

**Comment by parveendabas** [comment]
I am also ending up in several errors due to missing files like ".Rdata", "functions_general.vh20180105.R". 

Also, after downloading the data from Geo for BM cells, there are several columns in the annotation for e.g. "GSM3587996_BM1.anno.txt"



Cell | NumberOfReads | AlignedToGenome | AlignedToTranscriptome | TranscriptomeUMIs | NumberOfGenes | CyclingScore | CyclingBinary | MutTranscripts | WtTranscripts | PredictionRF2 | PredictionRefined | CellType | Score_HSC | Score_Prog | Score_GMP | Score_ProMono | Score_Mono | Score_cDC | Score_pDC | Score_earlyEry | Score_lateEry | Score_ProB | Score_B | Score_Plasma | Score_T | Score_CTL | Score_NK
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BM1_AAAGTCTCAAAC | 170122 | 112905 | 83112 | 2287 | 912 | -0.288 | no |   |   | normal | normal | cDC | 0.033 | 0.026 | 0.027 | 0.098 | 0.202 | 0.371 | 0.022 | 0.031 | 0.031 | 0.012 | 0.066 | 0.009 | 0.021 | 0.031 | 0.02


Here, the scores for 15 cell types like "Score_HSC" or "Score_Prog" are from RFclassifier or correlation scores after comparing all the single cells to 15 cell types?

I want to labels the single cells in my datasets but till now unsuccessful due to incomplete Rcodes and/or insufficient information.

**Comment by lagzxadr** [comment]
> ```
> tim@tim-ThinkPad-T470:~/Dropbox/TricheLab/TARGET_AML/Bernstein_scAML/aml2019/04 Random forest classifier$ Rscript 1_RFtrain.R
> randomForest 4.6-14
> Type rfNews() to see new features/changes/bug fixes.
> Error in file(filename, "r", encoding = encoding) : 
>   cannot open the connection
> Calls: source -> file
> In addition: Warning message:
> In file(filename, "r", encoding = encoding) :
>   cannot open file '/home/tim/DropboxPartners/Single-cell AML/Analysis/AnalysisVolker/functions_general.vh20180105.R': No such file or directory
> Execution halted
> ```
> 
> The other script in the directory also fails due to the .Rdata files not being available.
> 
> The paper is great, but the code is far from complete. Shame on the reviewers for not running any of it.

Hi,

Did you guys finally get the missing function files? Where to get?

Thanks!

**Comment by hovestadt** [comment]
Thank you everyone for comments and apologies for the late reply.

The functions file is not required to run the script, I removed the source command in the updated version.

The RData files contain processed gene expression matrices that are available on GEO (GSE116256, *dem.txt files). gene counts need to be normalized to 10,000 per column.

@parveendabas, the BackSPIN cell annotations are now provided in BM_6915cells.BackSPIN.txt.

**Comment by ttriche** [comment]
@hovestadt thanks so much for patching this up!  Per previous, the paper is great, which is why I'm back here looking at it yet again.  The inv(3) sample is of particular interest now :-)

Cheers!

**Comment by hovestadt** [comment]
hi @ttriche, glad it works now. thanks for the feedback!
